# on:
#   pull_request:
#   push:
#     branches:
#       - main

# name: Continuous Integration

# jobs:
  # test-coverage:
  #   name: Test coverage (PHPUnit)

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: "8.0"
  #         coverage: xdebug3
  #         tools: none

  #     - name: Install composer dependencies
  #       uses: ramsey/composer-install@1.3.0
  #       with:
  #         dependency-versions: locked
  #         composer-options: --no-ansi --no-interaction --no-progress

  #     - name: Calculate test coverage
  #       env:
  #         NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  #       run: vendor/bin/phpunit --coverage-clover dist/phpunit/clover.xml

  #     - name: Send code coverage report to Codecov.io
  #       uses: codecov/codecov-action@v1
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
