name: "Check Coding Standards"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coding-standards:
    name: "Check Coding Standards"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          tools: composer:v2, cs2pr

      - name: Install composer dependencies
        uses: ramsey/composer-install@1.3.0
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress

      - name: Run phpcs checks
        run: "composer ci:phpcs"