name: "Mutation tests"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  infection:
    name: "Mutation tests"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          coverage: "pcov"
          tools: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@1.3.0
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress

      - name: Run mutation tests with Infection
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: composer mutation-tests
