name: "Static Analysis (Psalm)"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  psalm:
    name: Psalm

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          tools: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@1.3.0
        with:
          dependency-versions: locked
          composer-options: --no-ansi --no-interaction --no-progress

      - name: Run tests with psalm and send coverage report
        run: composer ci:psalm